### ISSUE TITLE
Path to which

### ISSUE THREAD

**Issue by mrqwer88** [yadutaf/ctop#7]
Hello!
Not all distributive have alias /bin/which .
As example in Centos 6 - 

```
 LANG=C LC_ALL=C ls -l /bin/which /usr/bin/which
ls: cannot access /bin/which: No such file or directory
-rwxr-xr-x 1 root root 20768 Sep 23  2011 /usr/bin/which

```

As result ctop start failed with 

```
./ctop_orig 
Traceback (most recent call last):
  File "./ctop_orig", line 46, in <module>
    HAS_LXC = cmd_exists('lxc-start')
  File "./ctop_orig", line 44, in cmd_exists
    return subprocess.call(["/bin/which",  cmd], stdout=subprocess.PIPE, stderr=subprocess.PIPE) == 0
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(*popenargs, **kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

until the path to which will not be changed manually

**Comment by yadutaf** [comment]
Indeed, no path should be hard-coded. Will fix this ASAP. Thanks for the report.
